### ISSUE TITLE
"Task is null please check log for errors." in RU environment

### ISSUE THREAD

**Issue by thomasvoigt** [ere-health/ere-ps-app#39]
Hi there!

When trying to generate prescriptions for the RU environment, we get the following error: "Task is null please check log for errors."
The bundle is generated (XML file exists in LocalAppData), but we get no Access Code.

Log with stack trace: [ere.ps.txt](https://github.com/ere-health/ere-ps-app/files/7194742/ere.ps.txt)

Thanks and best regards,
Thomas

**Comment by ManuelB** [comment]
@thomasvoigt currently the domain service in the RU is disconnected from the domain service because load tests are executed:
![Bildschirmfoto von 2021-09-20 11-37-48](https://user-images.githubusercontent.com/457641/133985055-1a9154e4-527f-46c9-b34f-491e3deffa22.png)

Please try again tomorrow.

**Comment by thomasvoigt** [comment]
Hi @ManuelB, 

thanks for getting back to me so quickly, we will try again tomorrow.

Best regards,
Thomas

**Comment by thomasvoigt** [comment]
Hi @ManuelB,

IBM's loat tests seem to be over, as today I got past this error. 

Thank you!
