### ISSUE TITLE
"Aut idem" is inverted

### ISSUE THREAD

**Issue by thomasvoigt** [ere-health/ere-ps-app#42]
Hi @ManuelB,

the _aut idem_ flag in the UI seems to be inverted.

* _aut idem_ **not** selected: ![grafik](https://user-images.githubusercontent.com/6514700/134129280-8c352451-7015-4a47-b729-b91e0b7207db.png)
* yields the following JSON data:
```json
  "substitution": {
      "allowedBoolean": false
  }
```
* Preview and PDF reflect the inverted `"allowedBoolean": false` value:
[ere.health aut idem.pdf](https://github.com/ere-health/ere-ps-app/files/7201212/ere.health.aut.idem.pdf)
 
_Rahmenvertrag § 9 Abs. 1b_ states:
> Hat der Vertragsarzt […] die Ersetzung eines unter seinem Produktnamen verordneten Fertigarzneimittels durch ein wirkstoffgleiches Arzneimittel ausgeschlossen (= gesetztes aut-idem-Kreuz) […]

Yes, this definition is counterintuitive ;-)

Thanks and best regards,
Thomas

**Comment by ManuelB** [comment]
@thomasvoigt please try again. Should be fixed now.
