### ISSUE TITLE
How to get test Kim-Email with test HBA and SMC-B?

### ISSUE THREAD

**Issue by toghrulgasimov** [ere-health/ere-ps-app#53]
Hello as I see, you have test-kim emails https://github.com/ere-health/ere-ps-app/blob/4b969ec202eb2a0d71c9b6177c1857aa1185abee/src/test/resources/websocket-messages/SignAndUploadBundlesKIM.json#L606 .

We have test cads but we can't create kim-emails with their test telematikIds.  We get error  "Eintrag in VZD nicht gefunden".  
How did you solve this problem? 

Thanks in Advance.

**Comment by ManuelB** [comment]
Hi toghrulgasimov,
having the KIM address where you send the prescription (flowtype 169) to in the VZD is not required but expected.

You should register a KIM address with a typical RU address provider like Arvato, CGM or Akquinet. Your counterpart needs one aswell. Registering and activated the KIM address is complex.

If you need an offer for commercial support, let me know.

/Manuel

**Comment by toghrulgasimov** [comment]
Thanks for the answer, I could get a test domain from our provider.
