### ISSUE TITLE
Wrong Public Key Padding

### ISSUE THREAD

**Issue by tobias-schwerdtfeger** [ere-health/ere-ps-app#58]
Hey @ManuelB 

if the encoded key is less than 32 bytes you need to copy the array to the end of the 32 bytes. So the zeros stay at the beginning.

https://github.com/ere-health/ere-ps-app/blob/b5d4b226716b19a6d838b6f598de45046d7f85ab/src/main/java/health/ere/ps/vau/VAU.java#L274

So the result of encrypt should be something like `01 0000d062b4cd88537f817a3805c5d10fad684dde2f60c83af466427364ecdf15 03aa102d9bd1570b101decf30ef95a58c081c68bb3f5441864ed51ae538b6bc7 ...`

**Comment by ManuelB** [comment]
@tobias-schwerdtfeger thanks a lot for the hint. I will integrate this as fast as possible.
